# Generated by Django 5.2.3 on 2025-07-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('prediction', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('code', 'date')},
            },
        ),
    ]
